server:
  port:
    8080
  forward-headers-strategy: framework
  error:
    include-message: on-param
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        type:
          json_format_mapper: com.coffeeshop.config.hibernate.FormatMapperCustom
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: true